name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with: 
        version: 12
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
    # Yarn command
        cmd: install
    - name: Creating build
      run: yarn build
    
    - name: installing surge 
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://assign-ment-1.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
